system:
  device: 'cpu'
  confidence_threshold: 0.3
  iou_threshold: 0.45

camera:
  source: 0
  width: 1200
  height: 720

danger_zones:
  - name: "Khu vuc nguy hiem"
    points: [[0.2, 0.2], [0.8, 0.2], [0.8, 0.8], [0.2, 0.8]]
    color: [0, 0, 255]

alerts:
  sound_alert: true
  custom_sound_file: "canhbao.wav"
#  cooldown_seconds: 3        # ← Quan trọng: dùng tên này